### ISSUE TITLE
Label names are in the HTML. div class names changed?

### ISSUE THREAD

**Issue by CADbloke** [llad/labelize-for-trello#2]
Greetings.

I'd submit a pull request for this but I am even worse at JavaScript than I am at life so I'll just post my findings. 

The label names are in the `card-label` span, called `"Title"`, the appear on Hover so you probably don't need an API call. The `labelSelector` &  `cardSelector` divs seem to now be `div.list-card-labels`

Actually, I found that by simply disabling the `height` & `line-height` in `.list-card-labels` (using Chrome's Inspect Element) the titles came up.

The easiest way to show label names is to use Chrome Stylebot. I used this CSS:

````css
span.card-label {
    height: 10px;
    line-height: 10px;
    width: 65px
    font-weight: normal;
    font-size: 10px;
}
````
